INSERT INTO languages (channel_name, lang_name) VALUES ('Netflix India', 'Hindi');
INSERT INTO languages (channel_name, lang_name) VALUES ('Netflix India', 'English');
INSERT INTO languages (channel_name, lang_name) VALUES ('Netflix India', 'Bhojpuri');
INSERT INTO languages (channel_name, lang_name) VALUES ('Netflix India', 'Gujarati');
INSERT INTO languages (channel_name, lang_name) VALUES ('BBC UK', 'English');
INSERT INTO languages (channel_name, lang_name) VALUES ('CBC Canada', 'English');
INSERT INTO languages (channel_name, lang_name) VALUES ('ABC Australia', 'English');
INSERT INTO languages (channel_name, lang_name) VALUES ('Prime Video Germany', 'German');
INSERT INTO languages (channel_name, lang_name) VALUES ('Prime Video Germany', 'English');
INSERT INTO languages (channel_name, lang_name) VALUES ('TVNZ New Zealand', 'English');
INSERT INTO languages (channel_name, lang_name) VALUES ('Globo Brazil', 'Portuguese');
INSERT INTO languages (channel_name, lang_name) VALUES ('Globo Brazil', 'English');
